<?php

namespace Convo\Core\Adapters\Alexa;

use Convo\Core\Util\AbstractEnum;

final class AlexaSkillCategoriesEnum extends AbstractEnum
{
    public const ALARMS_AND_CLOCKS = "ALARMS_AND_CLOCKS";
    public const ASTROLOGY = "ASTROLOGY";
    public const BUSINESS_AND_FINANCE = "BUSINESS_AND_FINANCE";
    public const CALCULATORS = "CALCULATORS";
    public const CALENDARS_AND_REMINDERS = "CALENDARS_AND_REMINDERS";
    public const CHILDRENS_EDUCATION_AND_REFERENCE = "CHILDRENS_EDUCATION_AND_REFERENCE";
    public const CHILDRENS_GAMES = "CHILDRENS_GAMES";
    public const CHILDRENS_MUSIC_AND_AUDIO = "CHILDRENS_MUSIC_AND_AUDIO";
    public const CHILDRENS_NOVELTY_AND_HUMOR = "CHILDRENS_NOVELTY_AND_HUMOR";
    public const COMMUNICATION = "COMMUNICATION";
    public const CONNECTED_CAR = "CONNECTED_CAR";
    public const COOKING_AND_RECIPE = "COOKING_AND_RECIPE";
    public const CURRENCY_GUIDES_AND_CONVERTERS = "CURRENCY_GUIDES_AND_CONVERTERS";
    public const DATING = "DATING";
    public const DELIVERY_AND_TAKEOUT = "DELIVERY_AND_TAKEOUT";
    public const DEVICE_TRACKING = "DEVICE_TRACKING";
    public const EDUCATION_AND_REFERENCE = "EDUCATION_AND_REFERENCE";
    public const EVENT_FINDERS = "EVENT_FINDERS";
    public const EXERCISE_AND_WORKOUT = "EXERCISE_AND_WORKOUT";
    public const FASHION_AND_STYLE = "FASHION_AND_STYLE";
    public const FLIGHT_FINDERS = "FLIGHT_FINDERS";
    public const FRIENDS_AND_FAMILY = "FRIENDS_AND_FAMILY";
    public const GAME_INFO_AND_ACCESSORY = "GAME_INFO_AND_ACCESSORY";
    public const GAMES = "GAMES";
    public const HEALTH_AND_FITNESS = "HEALTH_AND_FITNESS";
    public const HOTEL_FINDERS = "HOTEL_FINDERS";
    public const KNOWLEDGE_AND_TRIVIA = "KNOWLEDGE_AND_TRIVIA";
    public const MOVIE_AND_TV_KNOWLEDGE_AND_TRIVIA = "MOVIE_AND_TV_KNOWLEDGE_AND_TRIVIA";
    public const MOVIE_INFO_AND_REVIEWS = "MOVIE_INFO_AND_REVIEWS";
    public const MOVIE_SHOWTIMES = "MOVIE_SHOWTIMES";
    public const MUSIC_AND_AUDIO_ACCESSORIES = "MUSIC_AND_AUDIO_ACCESSORIES";
    public const MUSIC_AND_AUDIO_KNOWLEDGE_AND_TRIVIA = "MUSIC_AND_AUDIO_KNOWLEDGE_AND_TRIVIA";
    public const MUSIC_INFO_REVIEWS_AND_RECOGNITION_SERVICE = "MUSIC_INFO_REVIEWS_AND_RECOGNITION_SERVICE";
    public const NAVIGATION_AND_TRIP_PLANNER = "NAVIGATION_AND_TRIP_PLANNER";
    public const NEWS = "NEWS";
    public const NOVELTY = "NOVELTY";
    public const ORGANIZERS_AND_ASSISTANTS = "ORGANIZERS_AND_ASSISTANTS";
    public const PETS_AND_ANIMAL = "PETS_AND_ANIMAL";
    public const PODCAST = "PODCAST";
    public const PUBLIC_TRANSPORTATION = "PUBLIC_TRANSPORTATION";
    public const RELIGION_AND_SPIRITUALITY = "RELIGION_AND_SPIRITUALITY";
    public const RESTAURANT_BOOKING_INFO_AND_REVIEW = "RESTAURANT_BOOKING_INFO_AND_REVIEW";
    public const SCHOOLS = "SCHOOLS";
    public const SCORE_KEEPING = "SCORE_KEEPING";
    public const SELF_IMPROVEMENT = "SELF_IMPROVEMENT";
    public const SHOPPING = "SHOPPING";
    public const SMART_HOME = "SMART_HOME";
    public const SOCIAL_NETWORKING = "SOCIAL_NETWORKING";
    public const SPORTS_GAMES = "SPORTS_GAMES";
    public const SPORTS_NEWS = "SPORTS_NEWS";
    public const STREAMING_SERVICE = "STREAMING_SERVICE";
    public const TAXI_AND_RIDESHARING = "TAXI_AND_RIDESHARING";
    public const TO_DO_LISTS_AND_NOTES = "TO_DO_LISTS_AND_NOTES";
    public const TRANSLATORS = "TRANSLATORS";
    public const TV_GUIDES = "TV_GUIDES";
    public const UNIT_CONVERTERS = "UNIT_CONVERTERS";
    public const WEATHER = "WEATHER";
    public const WINE_AND_BEVERAGE = "WINE_AND_BEVERAGE";
    public const ZIP_CODE_LOOKUP = "ZIP_CODE_LOOKUP";

    private function __construct()
    {
    }
}
